#!/usr/bin/env php
<?php

declare(strict_types=1);

use Maduser\AgentCli\AppKernel;

require dirname(__DIR__) . '/vendor/autoload.php';

$kernel = new AppKernel(dirname(__DIR__));

exit($kernel->run());
